version: 2
jobs:
  node:
    working_directory: ~/floriscope-mobile
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: Jest Unit Tests
          command: |
            yarn test -u

      - persist_to_workspace:
          root: ~/floriscope-mobile
          paths:
            - node_modules

workflows:
  version: 2
  node:
    jobs:
      - node
